fix: kubeconfig path

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,122 +5,139 @@ on:
 
 jobs:
 
-  sonarcloud:
-    name: SonarCloud
+  kubeconfig:
+    name: kubeconfig
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
 
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-
-  job-build:
-    needs:
-      - sonarcloud
-    runs-on: ubuntu-latest
-    steps:
-
-      - uses: actions/checkout@v2
-
-      - name: Cache local Maven repository
-        uses: actions/cache@v2
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-            - name: Cache local Maven repository
-
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
-        with:
-          java-version: 1.8
-
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-
-      - name: Prepare for execution of functionnal tests
-        run: |
-          git clone https://github.com/nuvla/example-ubuntu.git ${HOME}/example-ubuntu
-          git clone https://github.com/nuvla/example-centos.git ${HOME}/example-centos
-          git clone https://github.com/nuvla/example-rstudio.git ${HOME}/example-rstudio
-          git clone https://github.com/nuvla/example-jupyter.git ${HOME}/example-jupyter
-          git clone https://github.com/nuvla/example-app.git ${HOME}/example-app
-
-          pip install nuvla-api
-          python -c 'import nuvla.api;'
-
-      - name: Install kubectl
-        uses: azure/setup-kubectl@v1
-        with:
-          version: 'v1.19.5'
-        id: install-kubectl
-
-      - name: Deploy Kubernetes test cluster
-        env:
-          WORKERS_NUMBER: 1
-          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
-          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
-        run: |
-          cd k8s-cluster
-          ./cluster-deploy-exoscale.sh deploy $WORKERS_NUMBER
-
-      - name: Install Helm
-        uses: azure/setup-helm@v1
-        with:
-          version: 'v3.6.3'
-        id: install-helm
-
-      - name: Set WORKSPACE_PATH
-        run: echo ::set-env name=WORKSPACE_PATH::$GITHUB_WORKSPACE
+      - name: Set KUBECONFIG
+        run: echo "KUBECONFIG=${{ GITHUB_WORKSPACE }}/k8s-cluster/kubeconfig.yaml" >> $GITHUB_ENV
 
       - name: Deploy Nuvla
         env:
-          KUBECONFIG: ${{ env.WORKSPACE_PATH }}/k8s-cluster/kubeconfig.yaml
           WAIT_AVAIL_MIN: 5
         run: |
-          echo KUBECONFIG=$KUBECONFIG
-          cd test
-          helm install -n nuvla --create-namespace nuvla .
-          sleep 60
-          NUVLA_ENDPOINT=$(get-nuvla-endpoint.sh)
-          echo NUVLA_ENDPOINT=$NUVLA_ENDPOINT
-          ./wait-avail.sh ${NUVLA_ENDPOINT}/api/cloud-entry-point $WAIT_AVAIL_MIN || { >&2 echo "failed to provision Nuvla."; cd ../k8s-cluster/; ./cluster-deploy-exoscale.sh terminate; exit 1; }
+          echo kubeconfig=${{ env.KUBECONFIG }}
+          ls -l
 
-      - name: Run Nuvla functional tests
-        run: |
-          cd functional-tests
-          export EXAMPLES_ROOT=${HOME}
-          export NUVLA_INSECURE=TRUE
-          export NUVLA_HOST=$(cat $HOME/nuvla-test-host)
-          export SSH_PUBLIC_KEY=$HOME/.ssh/id_rsa.pub
-          export mname=$(cat $HOME/docker-machine-master)
-          eval $($HOME/docker-machine env $mname --shell bash)
-          lein do clean, test
-
-      - name: Terminate Kubernetes test cluster
-        if: ${{ always() }}
-        env:
-          BUILD_DIR: .
-          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
-          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
-        run: $BUILD_DIR/k8s-cluster/cluster-deploy-exoscale.sh terminate
-
-  job-notify:
-    if: always()
-    name: Post Workflow Status To Slack
-    needs:
-      - job-build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: Gamesight/slack-workflow-status@master
-        with:
-          repo_token: ${{secrets.GITHUB_TOKEN}}
-          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
+#  sonarcloud:
+#    name: SonarCloud
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+#
+#      - name: SonarCloud Scan
+#        uses: SonarSource/sonarcloud-github-action@master
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#
+#  job-build:
+#    needs:
+#      - sonarcloud
+#    runs-on: ubuntu-latest
+#    steps:
+#
+#      - uses: actions/checkout@v2
+#
+#      - name: Cache local Maven repository
+#        uses: actions/cache@v2
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#            - name: Cache local Maven repository
+#
+#      - name: Set up JDK 1.8
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 1.8
+#
+#      - name: Set up Python 3.9
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.9
+#
+#      - name: Prepare for execution of functionnal tests
+#        run: |
+#          git clone https://github.com/nuvla/example-ubuntu.git ${HOME}/example-ubuntu
+#          git clone https://github.com/nuvla/example-centos.git ${HOME}/example-centos
+#          git clone https://github.com/nuvla/example-rstudio.git ${HOME}/example-rstudio
+#          git clone https://github.com/nuvla/example-jupyter.git ${HOME}/example-jupyter
+#          git clone https://github.com/nuvla/example-app.git ${HOME}/example-app
+#
+#          pip install nuvla-api
+#          python -c 'import nuvla.api;'
+#
+#      - name: Install kubectl
+#        uses: azure/setup-kubectl@v1
+#        with:
+#          version: 'v1.19.5'
+#        id: install-kubectl
+#
+#      - name: Deploy Kubernetes test cluster
+#        env:
+#          WORKERS_NUMBER: 1
+#          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
+#          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
+#        run: |
+#          cd k8s-cluster
+#          ./cluster-deploy-exoscale.sh deploy $WORKERS_NUMBER
+#
+#      - name: Install Helm
+#        uses: azure/setup-helm@v1
+#        with:
+#          version: 'v3.6.3'
+#        id: install-helm
+#
+#      - name: Set KUBECONFIG
+#        run: echo "KUBECONFIG=${{ GITHUB_WORKSPACE }}" >> $GITHUB_ENV
+#
+#      - name: Deploy Nuvla
+#        env:
+#          WAIT_AVAIL_MIN: 5
+#        run: |
+#          echo kubeconfig=${{ env.KUBECONFIG }}
+#          cd test
+#          helm install --kubeconfig=${{ env.KUBECONFIG }} -n nuvla --create-namespace nuvla .
+#          sleep 60
+#          NUVLA_ENDPOINT=$(get-nuvla-endpoint.sh)
+#          echo NUVLA_ENDPOINT=$NUVLA_ENDPOINT
+#          ./wait-avail.sh ${NUVLA_ENDPOINT}/api/cloud-entry-point $WAIT_AVAIL_MIN || { >&2 echo "failed to provision Nuvla."; cd ../k8s-cluster/; ./cluster-deploy-exoscale.sh terminate; exit 1; }
+#
+#      - name: Run Nuvla functional tests
+#        run: |
+#          cd functional-tests
+#          export EXAMPLES_ROOT=${HOME}
+#          export NUVLA_INSECURE=TRUE
+#          export NUVLA_HOST=$(cat $HOME/nuvla-test-host)
+#          export SSH_PUBLIC_KEY=$HOME/.ssh/id_rsa.pub
+#          export mname=$(cat $HOME/docker-machine-master)
+#          eval $($HOME/docker-machine env $mname --shell bash)
+#          lein do clean, test
+#
+#      - name: Terminate Kubernetes test cluster
+#        if: ${{ always() }}
+#        env:
+#          BUILD_DIR: .
+#          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
+#          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
+#        run: $BUILD_DIR/k8s-cluster/cluster-deploy-exoscale.sh terminate
+#
+#  job-notify:
+#    if: always()
+#    name: Post Workflow Status To Slack
+#    needs:
+#      - job-build
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: Gamesight/slack-workflow-status@master
+#        with:
+#          repo_token: ${{secrets.GITHUB_TOKEN}}
+#          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
