deploy docker swarm test cluster for functional tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,9 +53,8 @@ jobs:
           git clone https://github.com/nuvla/example-rstudio.git ${HOME}/example-rstudio
           git clone https://github.com/nuvla/example-jupyter.git ${HOME}/example-jupyter
           git clone https://github.com/nuvla/example-app.git ${HOME}/example-app
-
           pip install nuvla-api
-          python -c 'import nuvla.api;'
+          python -c 'import nuvla.api'
 
       - name: Install kubectl
         uses: azure/setup-kubectl@v1
@@ -86,7 +85,6 @@ jobs:
           WAIT_AVAIL_MIN: 5
         run: |
           echo kubeconfig=${{ env.KUBECONFIG }}
-          cat ${{ env.KUBECONFIG }}
           cd test
           helm install --kubeconfig=${{ env.KUBECONFIG }} -n nuvla --create-namespace nuvla .
           sleep 60
@@ -94,18 +92,27 @@ jobs:
           echo NUVLA_ENDPOINT=$NUVLA_ENDPOINT
           ./wait-avail.sh ${NUVLA_ENDPOINT}/api/cloud-entry-point $WAIT_AVAIL_MIN
 
+      - name: Deploy Docker swarm testing cluster
+        env:
+          SWARM_SIZE: 0
+          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
+          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
+        run: |
+          cd test
+          ./swarm-deploy.sh deploy $SWARM_SIZE || { >&2 echo "failed to provision Docker swarm test cluster"; ./swarm-deploy.sh terminate; exit 1; }
+
       - name: Run Nuvla functional tests
         run: |
           cd functional-tests
           export EXAMPLES_ROOT=${HOME}
           export NUVLA_INSECURE=TRUE
-          export NUVLA_HOST=$(cat $HOME/nuvla-test-host)
+          export NUVLA_HOST=$(../test/get-nuvla-endpoint.sh | sed -e 's|http.*/||')
           export SSH_PUBLIC_KEY=$HOME/.ssh/id_rsa.pub
           export mname=$(cat $HOME/docker-machine-master)
           eval $($HOME/docker-machine env $mname --shell bash)
           lein do clean, test
 
-#      - name: Terminate Kubernetes test cluster
+#      - name: Terminate K8s test cluster
 #        if: ${{ always() }}
 #        env:
 #          BUILD_DIR: .
